- name: Build devcontainer 
  ansible.builtin.import_tasks: setup.yml

- name: Install fonts on host 
  ansible.builtin.import_tasks: fonts.yml

- name: Create DevContainer
  ansible.builtin.import_tasks: create.yml

