- name: Setup my workplace
  hosts: controlnodes

  pre_tasks:
    - name: Get user
      ansible.builtin.shell: whoami
      register: user
    - name: Get user id
      ansible.builtin.shell: id -u
      register: user_id
    - name: Get Ubuntu version
      ansible.builtin.shell: . /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}"
      register: ubuntu_version
    - name: Get Architecture
      ansible.builtin.shell: dpkg --print-architecture
      register: machine_architecture



  roles: 
    - role: common
    - role: docker
