- name: Disable default use of systems fonts
  community.general.dconf: 
    key: "/org/gnome/Ptyxis/use-system-font"
    value: false
    state: present

- name: Use Meslo LGS NF 10
  community.general.dconf: 
    key: "/org/gnome/Ptyxis/font-name"
    value: "'MesloLGS NF 10'"
    state: present
